# Mundo 6

In [ ]:
import numpy as np

In [ ]:
#todas as operações funcionam com os vetores.

array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])
array3 = np.array([2, 2])

lista_normal = [1, 1, 1, 1]
lista_normal2 = [4, 2, 6, 2]

print(array1 + array2)
print(lista_normal + lista_normal2)

In [ ]:
print(array1 + array3)

In [ ]:
#E se eu quiser somar um número só?

soma_a_todos_os_elementos = np.array([1, 1, 1, 1]) + 20

print(soma_a_todos_os_elementos)

[21 21 21 21]


In [ ]:
#todas as operações funcionam normal
array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])

subtracao = array1 - array2
divisao = array1/array2
multiplicacao = array1 * array2
exponenciacao = array1 ** array2

print(subtracao)
print(divisao)
print(multiplicacao)
print(exponenciacao)

[-3 -1 -5 -1]
[0.25       0.5        0.16666667 0.5       ]
[4 2 6 2]
[1 1 1 1]


In [ ]:
#Operações dentro do próprio vetor

vetor = np.array([1, 4, -4, -1, 2])

print(vetor)
print(vetor.sum())
print(vetor.max())
print(vetor.min())
print(np.abs(vetor))

[ 1  4 -4 -1  2]
2
4
-4
[1 4 4 1 2]


In [ ]:
#Estatisticas descritivas

vetor = np.array([1, 20, -4, -12, 2000])

media = np.mean(vetor)
mediana = np.median(vetor)
desvio_p = np.std(vetor)
var = np.var(vetor)

print(media) #media
print(mediana) #mediana
print(desvio_p) #desvio padrao
print(var) #variancia

401.0
1.0
799.56938410622
639311.2


In [ ]:
#matriz de correlação 

vetor2 = np.array([5, 4, 3, -5, 4])
vetor3 = np.array([2, 6, 7, -5, 1])

correlacao = np.corrcoef((vetor, vetor2, vetor3))

correlacao

array([[ 1.        ,  0.25471058, -0.13247913],
       [ 0.25471058,  1.        ,  0.76783876],
       [-0.13247913,  0.76783876,  1.        ]])

# Exercício

* Exercício 35: Faça um programa que o usuário digite a rentabilidade de ações, com quantas ações o usuário quiser. Transforme essas listas em arrays e devolva pro usuário:

        A média de rentabilidade da carteira.
        O Desvio padrão da carteira.
        A mediana de retornos da carteira.
        O maior retorno.
        O menor retorno.

In [11]:
import numpy as np

continuar = True
rentabilidades = np.array([])

while continuar:
    rentabilidade = float(input('Digite uma rentabilidade:'))

    rentabilidades = np.append(rentabilidades, rentabilidade)

    deseja_continuar = str(input("Deseja cadastrar mais rentabilidades? [S/N]")).lower()

    if deseja_continuar != "n" and deseja_continuar != "s":

        invalido = True

        while invalido:

            deseja_continuar = str(input("Por favor, digite um comando válido: [S/N]")).lower()

            if deseja_continuar == "n" or deseja_continuar == "s":

                break

    if deseja_continuar == "n":

        break

media = "{:.0%}".format(np.mean(rentabilidades))
mediana = "{:.0%}".format(np.median(rentabilidades))
desvio_p = "{:.0%}".format(np.std(rentabilidades))

print('Aqui estão as estatísticas das rentabilidades:')
print(f'Média: {media}')
print(f'Mediana: {mediana}')
print(f'Desvio padrão: {desvio_p}')
print(f'Rentabilidade máxima:{"{:.0%}".format(rentabilidades.max())}')
print(f'Rentabilidade mínima:{"{:.0%}".format(rentabilidades.min())}')




Aqui estão as estatísticas das rentabilidades:
Média: 48%
Mediana: 40%
Desvio padrão: 31%
Rentabilidade máxima:90%
Rentabilidade mínima:15%


# Galáxia 4

Fim do módulo do Numpy! Na galáxia 4 nós iremos abordar o módulo Pandas, a principal biblioteca de análise de dados que existe.
Vamos aprender a puxar cotações, criar médias móveis, tratar dados, ler planilhas de excel e muito mais. Te vejo lá!